### ISSUE TITLE
Server crash when putting block in stonecutter

### ISSUE THREAD

**Issue by LittleNetworkHack** [AlexIIL/SimplePipes#27]
Pretty much in title, the moment i put stone in stonecutter server crashes. I didnt test with other blocks.

Crash Log:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 10/16/19 2:46 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.class_1856.method_8101([Lnet/minecraft/class_1799;)Lnet/minecraft/class_1856;
	at alexiil.mc.mod.pipes.part.SimplePipeParts.generateBlockToFacadeCuttingRecipes(SimplePipeParts.java:90)
	at alexiil.mc.mod.pipes.part.SimplePipeParts.addFacadeRecipes(SimplePipeParts.java:80)
	at net.minecraft.class_1863.invoke(class_1863.java:572)
	at net.minecraft.class_1863.redirect$redirectCollect$zzo000(class_1863.java:564)
	at net.minecraft.class_1863.method_17877(class_1863.java:77)
	at net.minecraft.class_3971.method_17855(class_3971.java:183)
	at net.minecraft.class_3971.method_7609(class_3971.java:173)
	at net.minecraft.class_3971$1.method_5431(class_3971.java:79)
	at net.minecraft.class_1277.method_5447(class_1277.java:117)
	at net.minecraft.class_1735.method_7673(class_1735.java:80)
	at net.minecraft.class_1703.method_7593(class_1703.java:278)
	at net.minecraft.class_3244.method_12076(class_3244.java:1227)
	at net.minecraft.class_2813.method_12191(class_2813.java:33)
	at net.minecraft.class_2813.method_11054(class_2813.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:706)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows Server 2019 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4343891168 bytes (4142 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 12 total; -Xms6G -Xmx6G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled
	Fabric Mods: 
		appleskin: AppleSkin 1.0.7
		blue_endless_jankson: jankson +
		fabric: Fabric API 0.4.0+build.240-1.14
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: Fabric Commands (v0) 0.1.1+591e97ae42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.1+591e97ae42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+591e97ae42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.0+591e97ae42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.0+c877038942
		fabric-networking-v0: Fabric Networking (v0) 0.1.3+591e97ae42
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-particles-v1: fabric-particles-v1 0.1.1+c877038942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.1+c877038942
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.1+591e97ae42
		fabricloader: Fabric Loader 0.6.3+build.167
		foamfix: FoamFix 0.12.1
		inventorysorter: Inventory Sorter 1.5.7
		libblockattributes: LibBlockAttributes 0.5.0
		libblockattributes_core: LibBlockAttributes (Core) 0.5.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.5.0
		libblockattributes_items: LibBlockAttributes (Items) 0.5.0
		libmultipart: LibMultiPart 0.2.0
		libnetworkstack: Lib Network Stack 0.2.0
		minecraft: Minecraft 1.14.4
		simple_pipes: SimplePipeTest 0.2.0
		simple_pipes_dep_container: SimplePipeTest (Depedency Container) 0.2.0
		storagecabinet: Storage Cabinet 1.0.0
	Player Count: 1 / 20; [class_3222['MiLkii'/110, l='world', x=-1528.07, y=78.00, z=-293.50]]
	Data Packs: vanilla, fabric/fabric-mining-levels-v0, fabric/storagecabinet, fabric/simple_pipes
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by AlexIIL** [comment]
It looks like this is because `Ingredient.ofStacks` is client-side only, so I'll have to find an alternative.

**Comment by LittleNetworkHack** [comment]
Well, hope this helps. GL

**Comment by AlexIIL** [comment]
Ok, this should be fixed as of 0.3.4 (although I fixed it before and didn't update this issue, sorry)
