### ISSUE TITLE
disconnected after joining my server

### ISSUE THREAD

**Issue by MSandro** [AlexIIL/SimplePipes#58]
Hi, since the last update I can't join my server. Here are some error lines from the log:
```
java.lang.IllegalStateException: The part alexiil.mc.mod.pipes.part.FacadePart@5e7174ed doesn't have a valid index in it's container!
	at alexiil.mc.lib.multipart.impl.PartContainer$1.writeContext0(PartContainer.java:117) ~[libmultipart-0.6.0-b1dcffe2c15e4442.jar:?]
	at alexiil.mc.lib.multipart.impl.PartContainer$1.writeContext0(PartContainer.java:106) ~[libmultipart-0.6.0-b1dcffe2c15e4442.jar:?]
	at alexiil.mc.lib.net.ParentNetIdDuel.writeContext(ParentNetIdDuel.java:35) ~[libnetworkstack-0.5.0-daeb1913f799a93.jar:?]
	at alexiil.mc.lib.net.ParentNetIdSingle.writeContextCall(ParentNetIdSingle.java:115) ~[libnetworkstack-0.5.0-daeb1913f799a93.jar:?]
	at alexiil.mc.lib.net.ParentNetIdDuel.writeContextCall(ParentNetIdDuel.java:41) ~[libnetworkstack-0.5.0-daeb1913f799a93.jar:?]
	at alexiil.mc.lib.net.NetIdSignalK.send(NetIdSignalK.java:95) ~[libnetworkstack-0.5.0-daeb1913f799a93.jar:?]
	at alexiil.mc.lib.multipart.impl.MultipartBlockEntity.sendNetworkUpdate(MultipartBlockEntity.java:177) ~[libmultipart-0.6.0-b1dcffe2c15e4442.jar:?]
	at alexiil.mc.lib.multipart.impl.PartContainer.sendNetworkUpdateExcept(PartContainer.java:690) ~[libmultipart-0.6.0-b1dcffe2c15e4442.jar:?]
	at alexiil.mc.lib.multipart.api.MultipartContainer.sendNetworkUpdate(MultipartContainer.java:216) ~[libmultipart-0.6.0-b1dcffe2c15e4442.jar:?]
	at alexiil.mc.lib.multipart.api.AbstractPart.sendNetworkUpdate(AbstractPart.java:119) ~[libmultipart-0.6.0-b1dcffe2c15e4442.jar:?]
	at alexiil.mc.lib.multipart.api.AbstractPart.onBreak(AbstractPart.java:172) ~[libmultipart-0.6.0-b1dcffe2c15e4442.jar:?]
	at alexiil.mc.lib.multipart.impl.MultipartBlock.onBreak(MultipartBlock.java:362) ~[libmultipart-0.6.0-b1dcffe2c15e4442.jar:?]
	at alexiil.mc.lib.multipart.impl.MultipartBlock.onBreak(MultipartBlock.java:71) ~[libmultipart-0.6.0-b1dcffe2c15e4442.jar:?]
	at net.minecraft.class_3225.destroyBlock0(class_3225.java:5713) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.handler$dib000$destroyBlock(class_3225.java:5696) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:247) ~[intermediary-server.jar:?]
	at net.kyrptonaught.diggusmaximus.Excavate.isExcavatingAllowed(Excavate.java:69) ~[diggusmaximus-1.5.1-1.17.jar:?]
	at net.kyrptonaught.diggusmaximus.Excavate.excavateAt(Excavate.java:60) ~[diggusmaximus-1.5.1-1.17.jar:?]
	at net.kyrptonaught.diggusmaximus.Excavate.spread(Excavate.java:53) ~[diggusmaximus-1.5.1-1.17.jar:?]
	at net.kyrptonaught.diggusmaximus.Excavate.startExcavate(Excavate.java:45) ~[diggusmaximus-1.5.1-1.17.jar:?]
	at net.kyrptonaught.diggusmaximus.StartExcavatePacket.lambda$registerReceivePacket$0(StartExcavatePacket.java:27) ~[diggusmaximus-1.5.1-1.17.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by AlexIIL** [comment]
That's... really odd. Sadly I don't think updating LibMultiPart manually would fix this - although I am confused as to why updating simple pipes causes the issue - if you revet back to the previous version does it go away?
