### ISSUE TITLE
"payload too large for NORMAL packet size" on connection

### ISSUE THREAD

**Issue by ghost** [AlexIIL/SimplePipes#69]
In version 0.10.0 on mc 1.19.4 I randomly started getting this error on connection:

```
java.lang.IllegalArgumentException: Packet Payload too large for NORMAL packet size - was 70452, which is bigger than 65536!
at alexiil.mc.lib.net.InternalMsgUtil.wrapFullPayload(InternalMsgUtil.java:648) ~[libnetworkstack-0.9.0-41fbad7da4f81a12.jar:?]
at alexiil.mc.lib.net.InternalMsgUtil.send(InternalMsgUtil.java:604) ~[libnetworkstack-0.9.0-41fbad7da4f81a12.jar:?]
at alexiil.mc.lib.net.NetIdDataK.send(NetIdDataK.java:87) ~[libnetworkstack-0.9.0-41fbad7da4f81a12.jar:?]
at alexiil.mc.lib.net.NetIdDataK.send(NetIdDataK.java:53) ~[libnetworkstack-0.9.0-41fbad7da4f81a12.jar:?]
at alexiil.mc.lib.multipart.impl.MultipartBlockEntity.sendInitialData(MultipartBlockEntity.java:93) ~[libmultipart-0.10.0-aeb6823dcb127f1d.jar:?]
at net.minecraft.class_3898.handler$cdm000$libnetworkstack$postSendPackets(class_3898.java:8975) ~[server-intermediary.jar:?]
at net.minecraft.class_3898.method_18715(class_3898.java:1340) ~[server-intermediary.jar:?]
at net.minecraft.class_3898.method_17241(class_3898.java:919) ~[server-intermediary.jar:?]
at net.minecraft.class_3898.sendSpiralChunkWatchPackets(class_3898.java:8697) ~[server-intermediary.jar:?]
at net.minecraft.class_3898.method_18714(class_3898.java:8519) ~[server-intermediary.jar:?]
at net.minecraft.class_3898.method_18701(class_3898.java:1215) ~[server-intermediary.jar:?]
at net.minecraft.class_3215.method_18755(class_3215.java:482) ~[server-intermediary.jar:?]
at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1541) ~[server-intermediary.jar:?]
at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1519) ~[server-intermediary.jar:?]
at net.minecraft.class_5579.method_31847(class_5579.java:217) ~[server-intermediary.jar:?]
at net.minecraft.class_5579.method_31820(class_5579.java:187) ~[server-intermediary.jar:?]
at net.minecraft.class_5579.method_31818(class_5579.java:168) ~[server-intermediary.jar:?]
at net.minecraft.class_3218.method_18771(class_3218.java:885) ~[server-intermediary.jar:?]
at net.minecraft.class_3218.method_18213(class_3218.java:871) ~[server-intermediary.jar:?]
at net.minecraft.class_3324.method_14570(class_3324.java:255) ~[server-intermediary.jar:?]
at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
at net.minecraft.class_3248.mdffaca5$polymer-networking$lambda$polymerNet$prePlayHandshakeHackfest$0$0(class_3248.java:4049) ~[server-intermediary.jar:?]
at eu.pb4.polymer.networking.impl.EarlyConnectionMagic.lambda$handle$0(EarlyConnectionMagic.java:28) ~[polymer-networking-0.4.0+1.19.4-7b8e4f635e617f39.jar:?]
at eu.pb4.polymer.networking.api.EarlyPlayNetworkHandler.lambda$onKeepAlive$0(EarlyPlayNetworkHandler.java:106) ~[polymer-networking-0.4.0+1.19.4-7b8e4f635e617f39.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:786) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:10328) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:762) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:746) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.handler$zme000$carpet$modifiedRunLoop(MinecraftServer.java:11945) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by ghost** [comment]
I managed to enter the world with another username and I found out that the problem was in a single chunk and the missed packet did not crash the client but made it behave weirdly (one or more chunks not showing, phantom blocks)

I suppose the problem was in a single misplaced pipe that had way too many items in it

I ended up opening the world in an external editor and removing all pipes from that chunk, and it fixed the situation

Still, I'll leave this open, just adding more info

**Comment by Dylusion** [comment]
Having this same issue but on 1.20.1, same exact error log

**Comment by Krischan-Klug** [comment]
same here pls fix this :( 1.20.1 - 0.11.0

**Comment by Kneelawk** [comment]
This should be fixed on 1.21.

**Comment by Krischan-Klug** [comment]
possible to fix 1.20.1 or maybe seperate the lib from the actual mod? think alot of modpacks will stay on older versions.

**Comment by sevenc-nanashi** [comment]
fyi: I fixed (ported 3 commits) in my fork, and my fork works on 1.20.1.

Built jar: [SimplePipes-0.11.0-pre.2.jar.zip](https://github.com/user-attachments/files/20746005/SimplePipes-0.11.0-pre.2.jar.zip) (I have no experience with modding so I used `gradlew build`, but there might be a command to build an optimized jar, idk)

If you don't trust me, you can build the modified version on your computer, using this source: https://github.com/sevenc-nanashi/SimplePipes/tree/0.11.x-1.20.x

I don't know if the problem on my client is same as yours, but at least my fork survived this test:

![Image](https://github.com/user-attachments/assets/3611250f-351e-4d12-a9ff-750b71baefbc)
