### ISSUE TITLE
Breaking a pipe causes items to disappear when broken or dropped

### ISSUE THREAD

**Issue by Rasttny** [AlexIIL/SimplePipes#71]
Server throws up this message once a pipe has been broken/mined causing all broken/dropped items to not spawn on breaking/throwing into the world.

[23:54:42] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2846@7241a40e, suppressing error
java.lang.IllegalStateException: The part alexiil.mc.mod.pipes.pipe.PartSpPipe@2da4edd2 doesn't have a valid index in it's container!
        at alexiil.mc.lib.multipart.impl.PartContainer$1.writeContext0(PartContainer.java:134) ~[libmultipart-0.11.0-pre.2-93dfa2b5c3381d10.jar:?]
        at alexiil.mc.lib.multipart.impl.PartContainer$1.writeContext0(PartContainer.java:123) ~[libmultipart-0.11.0-pre.2-93dfa2b5c3381d10.jar:?]
        at alexiil.mc.lib.net.ParentNetIdDuel.writeContext(ParentNetIdDuel.java:35) ~[libnetworkstack-0.10.0-pre.2-e58cda224a993bd5.jar:?]
        at alexiil.mc.lib.net.ParentNetIdSingle.writeContextCall(ParentNetIdSingle.java:115) ~[libnetworkstack-0.10.0-pre.2-e58cda224a993bd5.jar:?]
        at alexiil.mc.lib.net.ParentNetIdDuel.writeContextCall(ParentNetIdDuel.java:41) ~[libnetworkstack-0.10.0-pre.2-e58cda224a993bd5.jar:?]
        at alexiil.mc.lib.net.NetIdSignalK.send(NetIdSignalK.java:95) ~[libnetworkstack-0.10.0-pre.2-e58cda224a993bd5.jar:?]
        at alexiil.mc.lib.multipart.impl.MultipartBlockEntity.sendNetworkUpdate(MultipartBlockEntity.java:198) ~[libmultipart-0.11.0-pre.2-93dfa2b5c3381d10.jar:?]
        at alexiil.mc.lib.multipart.impl.PartContainer.sendNetworkUpdateExcept(PartContainer.java:863) ~[libmultipart-0.11.0-pre.2-93dfa2b5c3381d10.jar:?]
        at alexiil.mc.lib.multipart.api.MultipartContainer.sendNetworkUpdate(MultipartContainer.java:236) ~[libmultipart-0.11.0-pre.2-93dfa2b5c3381d10.jar:?]
        at alexiil.mc.lib.multipart.api.AbstractPart.sendNetworkUpdate(AbstractPart.java:134) ~[libmultipart-0.11.0-pre.2-93dfa2b5c3381d10.jar:?]
        at alexiil.mc.lib.multipart.api.AbstractPart.onBreak(AbstractPart.java:211) ~[libmultipart-0.11.0-pre.2-93dfa2b5c3381d10.jar:?]
        at alexiil.mc.lib.multipart.impl.MultipartBlock.onBreak(MultipartBlock.java:480) ~[libmultipart-0.11.0-pre.2-93dfa2b5c3381d10.jar:?]
        at alexiil.mc.lib.multipart.impl.MultipartBlock.onBreak(MultipartBlock.java:82) ~[libmultipart-0.11.0-pre.2-93dfa2b5c3381d10.jar:?]
        at net.minecraft.class_3225.destroyBlock0(class_3225.java:5223) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.handler$dli000$libmultipart$destroyBlock(class_3225.java:5206) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14266(class_3225.java:255) ~[server-intermediary.jar:?]
        at dev.ftb.mods.ftbultimine.FTBUltimine.blockBroken(FTBUltimine.java:239) ~[ftb-ultimine-fabric-2001.1.5.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-9.2.14-fabric.jar:?]
        at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:81) ~[architectury-9.2.14-fabric.jar:?]
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-31.1-jre.jar:?]
        at jdk.proxy2.$Proxy283.breakBlock(Unknown Source) ~[?:?]
        at net.minecraft.class_3225.handler$zlp000$architectury$onBreak(class_3225.java:2050) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14266(class_3225.java:243) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_21717(class_3225.java:228) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java:203) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1083) ~[server-intermediary.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:15818) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bni000$carpet$modifiedRunLoop(MinecraftServer.java:18451) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Kneelawk** [comment]
What other mods are you playing with? This sounds like the incompatibility with ChunkSending.
