### ISSUE TITLE
Crash on Multiplayer Server when placing a pipe

### ISSUE THREAD

**Issue by hfandre** [AlexIIL/SimplePipes#75]
Hi, i have the following issue.

When placing a pipe our server crashes, placing and using pipes in singleplayer works.
I already tested it on a diffrent server with only SimplePipes and Fabric installed, it resoveld in the same issue.

Thanks in Advance for your help!

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-11-10 04:03:15
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
	at knot//alexiil.mc.mod.pipes.pipe.PipeSpFlowItem.writeToBuffer(PipeSpFlowItem.java:123)
	at knot//alexiil.mc.mod.pipes.pipe.PartSpPipe.writeToBuffer(PartSpPipe.java:137)
	at knot//alexiil.mc.mod.pipes.pipe.PartSpPipe.writeCreationData(PartSpPipe.java:143)
	at knot//alexiil.mc.lib.multipart.impl.PartHolder.writeCreation(PartHolder.java:195)
	at knot//alexiil.mc.lib.multipart.impl.PartContainer.lambda$addPartInternal$3(PartContainer.java:440)
	at knot//alexiil.mc.lib.net.NetIdDataK.send(NetIdDataK.java:78)
	at knot//alexiil.mc.lib.multipart.impl.MultipartBlockEntity.sendNetworkUpdate(MultipartBlockEntity.java:223)
	at knot//alexiil.mc.lib.multipart.impl.PartContainer.sendNetworkUpdateExcept(PartContainer.java:870)
	at knot//alexiil.mc.lib.multipart.api.MultipartContainer.sendNetworkUpdate(MultipartContainer.java:242)
	at knot//alexiil.mc.lib.multipart.impl.PartContainer.addPartInternal(PartContainer.java:439)
	at knot//alexiil.mc.lib.multipart.impl.MultipartUtilImpl$1.apply(MultipartUtilImpl.java:149)
	at knot//alexiil.mc.mod.pipes.items.ItemSimplePart.method_7884(ItemSimplePart.java:48)
	at knot//net.minecraft.class_1799.method_7981(class_1799.java:373)
	at knot//net.minecraft.class_3225.method_14262(class_3225.java:372)
	at knot//net.minecraft.class_3244.method_12046(class_3244.java:1158)
	at knot//net.minecraft.class_2885.method_12547(class_2885.java:42)
	at knot//net.minecraft.class_2885.method_11054(class_2885.java:10)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
	at knot//net.minecraft.class_1255.method_18857(class_1255.java:145)
	at knot//net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 32 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3232984848 bytes (3083 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X3D 8-Core Processor           
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1080 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 11264.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MiB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.00
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MiB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.00
	Memory slot #3 type: DDR4
	Virtual memory max (MiB): 38125.96
	Virtual memory used (MiB): 25286.29
	Swap memory total (MiB): 5432.37
	Swap memory used (MiB): 78.74
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 34024.26, total: 457197.91
	Space in storage for workdir (MiB): available: 34024.26, total: 457197.91
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	Fabric Mods: 
		fabric-api: Fabric API 0.107.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.69+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.17+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+7fd4837519
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+e49211d819
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.22+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+0f6c53cd19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: Java HotSpot(TM) 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.13.0-pre.3
			libblockattributes: LibBlockAttributes 0.16.0-pre.2
				libblockattributes_core: LibBlockAttributes (Core) 0.16.0-pre.2
				libblockattributes_fluids: LibBlockAttributes (Fluids) 0.16.0-pre.2
				libblockattributes_items: LibBlockAttributes (Items) 0.16.0-pre.2
			libmultipart: LibMultiPart 0.13.0-pre.2
			libmultipart_compat: LibMultiPart (Mod Compatibility) 0.13.0-pre.2
			libnetworkstack: Lib Network Stack 0.13.0-pre.1
			simple_pipes: SimplePipeTest 0.13.0-pre.3
	Server Running: true
	Player Count: 1 / 20; [class_3222['SpitzkopfLarry14'/11, l='ServerLevel[world]', x=-52.08, y=81.00, z=26.75]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, simple_pipes
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, simple_pipes, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -4876447655503663299
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Kneelawk** [comment]
This was due to a typo when fixing #69. I'll have a fix out shortly.

**Comment by Kneelawk** [comment]
Ok, this should be fixed in version `[1.21.1] 0.13.0` now, which is available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/simplepipes/files/5897218) and [Modrinth](https://modrinth.com/mod/simple-pipes/version/0.13.0).
